apiVersion: v1
kind: ServiceAccount
metadata:
  name: sega-external-secrets
  namespace: sega
  annotations:
    iam.gke.io/gcp-service-account: sega-external-secrets@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: sega-gcp-secretsmanager
  namespace: sega
spec:
  provider:
    gcpsm:
      projectID: PROJECT_ID
      auth:
        workloadIdentity:
          clusterLocation: europe-west1
          clusterName: sega-prod
          serviceAccountRef:
            name: sega-external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sega-app-secrets
  namespace: sega
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: sega-gcp-secretsmanager
  target:
    name: sega-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: sega-prod-backend-DATABASE_PASSWORD
        version: latest
    - secretKey: DATABASE_URL
      remoteRef:
        key: sega-prod-backend-DATABASE_URL
        version: latest
    - secretKey: JWT_ACCESS_PRIVATE_KEY
      remoteRef:
        key: sega-prod-backend-JWT_ACCESS_PRIVATE_KEY
        version: latest
    - secretKey: JWT_ACCESS_PUBLIC_KEY
      remoteRef:
        key: sega-prod-backend-JWT_ACCESS_PUBLIC_KEY
        version: latest
    - secretKey: JWT_REFRESH_PRIVATE_KEY
      remoteRef:
        key: sega-prod-backend-JWT_REFRESH_PRIVATE_KEY
        version: latest
    - secretKey: JWT_REFRESH_PUBLIC_KEY
      remoteRef:
        key: sega-prod-backend-JWT_REFRESH_PUBLIC_KEY
        version: latest
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: sega-prod-backend-MINIO_ACCESS_KEY
        version: latest
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: sega-prod-backend-MINIO_SECRET_KEY
        version: latest
