input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if ![service] {
    mutate {
      add_field => { "service" => "sega-backend" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "sega-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
