apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../core.yaml
  - ../../observability.yaml
  - ../../logging.yaml
  - pvc.yaml
  - tls-issuer.yaml

patchesStrategicMerge:
  - patch-delete-local-secret.yaml
  - patch-ingress-tls.yaml
  - patch-minio-pvc.yaml
  - patch-prometheus-pvc.yaml
