apiVersion: v1
kind: ServiceAccount
metadata:
  name: sega-external-secrets
  namespace: sega
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/sega-external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: sega-aws-secretsmanager
  namespace: sega
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: sega-external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sega-app-secrets
  namespace: sega
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: sega-aws-secretsmanager
  target:
    name: sega-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: /sega/prod/backend
        property: DATABASE_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: /sega/prod/backend
        property: DATABASE_URL
    - secretKey: JWT_ACCESS_PRIVATE_KEY
      remoteRef:
        key: /sega/prod/backend
        property: JWT_ACCESS_PRIVATE_KEY
    - secretKey: JWT_ACCESS_PUBLIC_KEY
      remoteRef:
        key: /sega/prod/backend
        property: JWT_ACCESS_PUBLIC_KEY
    - secretKey: JWT_REFRESH_PRIVATE_KEY
      remoteRef:
        key: /sega/prod/backend
        property: JWT_REFRESH_PRIVATE_KEY
    - secretKey: JWT_REFRESH_PUBLIC_KEY
      remoteRef:
        key: /sega/prod/backend
        property: JWT_REFRESH_PUBLIC_KEY
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: /sega/prod/backend
        property: MINIO_ACCESS_KEY
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: /sega/prod/backend
        property: MINIO_SECRET_KEY
